### ISSUE TITLE
Find whether Fotmob or FBref is better to scrape data from

### ISSUE THREAD

**Issue by nanodino** [nanodino/nwsl-fantasy-helper#1]

**Comment by krcm17** [comment]
i think with either one, you would have to do it box score by box score.

**Comment by nanodino** [comment]
yeah for sure, it's a matter of which one has a more predictable way to handle match URLs, and secondarily which one has easier to parse HTML. The worst thing that can happen is I write a script and it fails to find some games.

**Comment by nanodino** [comment]
strange behaviour when using fotmob:

`driver.find_element_by_id("MatchFactsWrapper")` works in debug mode but not when invoked from within the code.

It's also clear fbref would be easier to scrape based on how the data is presented. I'm closing this issue, we can determine whether moving to fotmob is worth it once we have a working program.
